### ISSUE TITLE
Undefined variable $create_users causing no users to be created

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-attach-accounts-to-orders#1]
There's a bug in here where the query string passed is `create_users`, and we assign that like this:
`$create   = isset( $_GET['create_users'] ) ? absint( $_GET['create_users'] ) : 0;`

However in the loop, it's looking for `$create_users`
`if ( $create_users ){`

**Comment by cklosowski** [comment]
This might be a good issue to integrate with the new customers API as well.

**Comment by chriscct7** [comment]
Yeah that was pointed out to me tonight (the customers api one).
